"""empty message

Revision ID: 9882ff44d62d
Revises: 5fd764d0adfa
Create Date: 2025-04-30 22:50:55.400265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9882ff44d62d'
down_revision = '5fd764d0adfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship_model', schema=None) as batch_op:
        batch_op.drop_constraint('friendship_model_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('friendship_model_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship_model', schema=None) as batch_op:
        batch_op.create_foreign_key('friendship_model_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('friendship_model_ibfk_1', 'user', ['friend_id'], ['id'])

    # ### end Alembic commands ###
